version: "3"
services:
  app:
    image: "golang:1.17.6-alpine3.15"
    environment:
      DISCORD_BOT_ID: $DISCORD_BOT_ID
    volumes:
      - "./app:/app"
    working_dir: "/app"
    command: >
      sh -c '
      go build -o /usr/local/bin/bot &&
      /usr/local/bin/bot'
